vich_uploader:
    db_driver: orm

    mappings:
        enterprise_image:
            uri_prefix: /uploads/enterprise
            upload_destination: '%kernel.project_dir%/public/uploads/enterprise'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        user_image:
            uri_prefix: /uploads/user
            upload_destination: '%kernel.project_dir%/public/uploads/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    metadata:
        type: attribute